services:
  postgres:
    image: postgres:16-alpine
    container_name: carebridge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medsecure
      POSTGRES_USER: medsecure_user
      POSTGRES_PASSWORD: medsecure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

volumes:
  postgres_data: